name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23lihHL7Hgylqdatiu"
GITHUB_OWNER = "schzene"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://web.0xc0de.top/api/auth"
NEXT_PUBLIC_API_URL="https://web.0xc0de.top/"

